[tools]
"cargo:forgejo-cli" = "latest"
fzf = "latest"
gh = "latest"
"github:aria2/aria2" = "latest"
"github:pnpm/pnpm" = "12.3.4"
"github:sharkdp/fd" = "10.5.0"
go = "latest"
java = "temurin-25"
neovim = "stable"
node = "26.8.1"
ripgrep = "latest"
tmux = "latest"
uv = "latest"
