# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# Upgrade $TERM
set -g terminal-overrides ',xterm-256color:RGB'
set -g default-terminal "${TERM}"

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

## Keybindings

# Use vi keybindings
set -g mode-keys vi

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window
